language: java
jdk: oraclejdk11
os: linux
addons:
  mariadb: '10.4'
git:
  depth: 1
  quiet: true

before_install:
  - sudo mysql -u root --password="" < ../predicting-refactoring-ml/scripts/mariadb_settings.sql

jobs:
  include:
    - stage: Test
      name: "Test refactoringml - Data-Collection: Java"
      install:
        - cd ../predicting-refactoring-ml/data-collection/
        - mvn -f pom.xml -q -DskipTests clean compile package
      script: mvn -f pom.xml -Dtest=refactoringml.*Test test

    - name: "Test Integration Toyproject - Data-Collection: Java"
      install:
        - cd ../predicting-refactoring-ml/data-collection/
        - mvn -f pom.xml -q -DskipTests clean compile package
      script: mvn -f pom.xml -Dtest=integration.toyprojects.*Test test

    - name: "Test Integration Realproject ApacheCommonsCli - Data-Collection: Java"
      install:
        - cd ../predicting-refactoring-ml/data-collection/
        - mvn -f pom.xml -q -DskipTests clean compile package
      script: mvn -f pom.xml -Dtest=integration.realprojects.ApacheCommonsCli*Test test

    - name: "Test Integration Realproject ApacheCommonsCSV - Data-Collection: Java"
      install:
        - cd ../predicting-refactoring-ml/data-collection/
        - mvn -f pom.xml -q -DskipTests clean compile package
      script: mvn -f pom.xml -Dtest=integration.realprojects.ApacheCommonsCSV*Test test

    - name: "Run Canary ReactiveLocationIntegrationTest - Data-Collection: Java"
      install:
        - cd ../predicting-refactoring-ml/data-collection/
        - mvn -f pom.xml -q -DskipTests clean compile package
      script: mvn -f pom.xml -Dtest=integration.canaryprojects.ReactiveLocationIntegrationTest test

    - name: "Test machine-learning - Machine-Learning: Python"
      language: python
      python: "3.8"
      install:
        - cd ../predicting-refactoring-ml/machine-learning/
        - pip install -r requirements.txt
      script: pytest